[package]
name = "ftoc"
version = "1.0.0"
edition = "2021"
authors = ["Ethan Raque"]
description = "Converts farenheit to celcius"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0.13", features = ["derive"] }
